# see https://github.com/ankane/blazer for more info

data_sources:
  main:
    url: <%= ENV["BLAZER_DATABASE_URL"] %>

    # statement timeout, in seconds
    # applies to PostgreSQL only
    # none by default
    # timeout: 15

    # time to cache results, in minutes
    # can greatly improve speed
    # none by default
    # cache: 60

    # wrap queries in a transaction for safety
    # not necessary if you use a read-only user
    # true by default
    # use_transaction: false

    smart_variables:
      # zone_id: "SELECT id, name FROM zones ORDER BY name ASC"

    linked_columns:
      record_id: "/records/{value}"
      label_id: "/labels/{value}"

    smart_columns:
      record_id: "SELECT id, comment FROM records WHERE id IN {value}"
      artist_id: "SELECT id, name FROM artists WHERE id IN {value}"
      genre_id: "SELECT id, name FROM genres WHERE id IN {value}"
      label_id: "SELECT id, name FROM labels WHERE id IN {value}"
      record_format_id: "SELECT id, name FROM record_formats WHERE id IN {value}"

# create audits
audit: true

# change the time zone
time_zone: "Central Time (US & Canada)"

# class name of the user model
user_class: User

# method name for the user model
user_name: name

# email to send checks from
from_email: blazer@recordtemple.com
