development:
  adapter: postgresql
  database: recordtemple_dev
  host: localhost
 
test:
  adapter: postgresql
  database: recordtemple_test
  host: localhost
 
production:
  adapter: postgresql
  database: recordtemple_production
  host: localhost
  