development:
  bucket_name: recordtemple.com
  access_key_id: AKIAJHUEATTBX4CZX3CQ
  secret_access_key: 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
  distribution_domain: recordtemple.com.s3.amazonaws.com
  bucket: recordtemple.com

test:
  bucket_name: recordtemple.com
  access_key_id: AKIAJHUEATTBX4CZX3CQ
  secret_access_key: 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
  distribution_domain: recordtemple.com.s3.amazonaws.com

production:
  bucket_name: recordtemple.com
  access_key_id: AKIAJHUEATTBX4CZX3CQ
  secret_access_key: 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
  distribution_domain: recordtemple.com.s3.amazonaws.com
