development:
  bucket_name: recordtemple.com
  access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  distribution_domain: recordtemple.com.s3.amazonaws.com

test:
  bucket_name: recordtemple.com
  access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  distribution_domain: recordtemple.com.s3.amazonaws.com

production:
  bucket_name: recordtemple.com
  access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  distribution_domain: recordtemple.com.s3.amazonaws.com
